### PR TITLE
Added the copy-to-clipboard functionality for error messages and fixed the key warning.

### LINKED ISSUE #656: Support for copying text of error in error dropdown when expanded via clipboard icon

### PR DESCRIPTION
**Pull request by rushabhcodes**
This pull request enhances the user experience in the `ToolbarOverlay` component by adding a convenient "copy to clipboard" feature for error messages. It also includes some code organization improvements. The most important changes are:

**New Feature: Error Message Copying**
- Added a "copy to clipboard" icon next to each error message in the error list. When clicked, this copies the error message and briefly displays a "Copied!" confirmation. [[1]](diffhunk://#diff-2884ae32d92740f5f4934900becc1d4193fe4911bff5ee246038e2a85d24bdc3R246-R248) [[2]](diffhunk://#diff-2884ae32d92740f5f4934900becc1d4193fe4911bff5ee246038e2a85d24bdc3R657-R696)

**UI/UX Improvements**
- Adjusted the styling of the error message container to make room for the new copy icon and ensure proper positioning. [[1]](diffhunk://#diff-2884ae32d92740f5f4934900becc1d4193fe4911bff5ee246038e2a85d24bdc3R645) [[2]](diffhunk://#diff-2884ae32d92740f5f4934900becc1d4193fe4911bff5ee246038e2a85d24bdc3R657-R696)

**Code Organization**
- Cleaned up and reordered imports for clarity and to group related dependencies together.
- Improved the use of keys in error message rendering by switching from the array index to a unique `errorId` for better React performance and stability.

Screenshot_20260211_144110

image

/fix #656

### CODE REVIEW

**Review by Abse2001 — COMMENTED** [review]
Didn't work on mobile for me, make sure it works on mobile too.
https://pcb-viewer-git-fork-rushabhcodes-add-copy-to-c-97a03c-tscircuit.vercel.app/?fixture=%7B%22path%22%3A%22src%2Fexamples%2F2025%2Flong-line-errors.fixture.tsx%22%7D

File: src/hooks/useMobileTouch.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ * when using both click and touch handlers.
+ */
+export const useMobileTouch = (
+  onClick?: (e: any) => void,
+  options: { stopPropagation?: boolean } = { stopPropagation: true },
+) => {
+  const lastInteractionRef = useRef(0)
+
+  const handleInteraction = useCallback(
+    (e: any) => {
```
Comment (Abse2001) [inline src/hooks/useMobileTouch.ts]: try no to use any casting

**Comment by Abse2001** [comment]
@rushabhcodes fix the type check too
