### PR TITLE
fix: touch to interact work on mobile

### LINKED ISSUE #251: Click to interact doesnt work on mobile
Image

/bounty $5

### LINKED ISSUE #253: On mobile display “Touch to Interact” instead of Click to Interact

### PR DESCRIPTION
**Pull request by krushnarout**
fixes #251 
closes #253 
/claim #251

https://github.com/user-attachments/assets/3a723599-46b0-4028-9576-244b55746299

### CODE REVIEW

File: src/PCBViewer.tsx [hunk 1]
```diff
@@ -160,6 +160,41 @@ export const PCBViewer = ({
             setIsInteractionEnabled(true)
             resetTransform()
           }}
+          onTouchStart={(e) => {
+            const touch = e.touches[0]
+            e.currentTarget.setAttribute(
+              "data-touch-start-x",
+              touch.clientX.toString(),
+            )
```
Comment (seveibar) [inline src/PCBViewer.tsx:168]: you should store this using a useRef

File: src/PCBViewer.tsx [hunk 2]
```diff
@@ -180,7 +216,9 @@ export const PCBViewer = ({
               pointerEvents: "none",
             }}
           >
-            Click to Interact
+            {typeof window !== "undefined" && window.innerWidth < 768
```
Comment (seveibar) [inline src/PCBViewer.tsx:219]: not sure i like this approach using window size, it's ok but is there not a better way to detect touch devices? Ipads would fail this test for example

File: src/PCBViewer.tsx [hunk 3]
```diff
@@ -168,6 +192,7 @@ export const PCBViewer = ({
             display: "flex",
             alignItems: "center",
             justifyContent: "center",
+            touchAction: "pan-x pan-y",
```
Comment (seveibar) [inline src/PCBViewer.tsx:195]:
```suggestion
            touchAction: "pan-x pan-y pinch-zoom",
```

**Review by seveibar — APPROVED** [review]
