### PR TITLE
Fix multi-layer visibility issues: inner5,6 not showing and top layer…

### LINKED ISSUE #398: Inner5 and Inner6 Layers Not Visible (Opacity 0.5) Unless Selected in LayerSelect Toolbar
Here is the example where you cant see the inner5 and inner6 layers.

Image

<details>
<summary>JSON to reproduce the issue</summary>

{
      type: "pcb_board",
      pcb_board_id: "pcb_board_0",
      center: { x: 0, y: 0 },
      width: 60,
      height: 25,
      material: "fr4",
      num_layers: 8,
      thickness: 1.6,
    },
    // Single pad on top layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_top",
      x: -21,
      y: 0,
      width: 2,
      height: 1,
      layer: "top",
      shape: "rect",
    },
    // Single pad on inner1 layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_inner1",
      x: -15,
      y: 0,
      width: 2,
      height: 1,
      layer: "inner1",
      shape: "rect",
    },
    // Single pad on inner2 layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_inner2",
      x: -9,
      y: 0,
      width: 2,
      height: 1,
      layer: "inner2",
      shape: "rect",
    },
    // Single pad on inner3 layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_inner3",
      x: -3,
      y: 0,
      width: 2,
      height: 1,
      layer: "inner3",
      shape: "rect",
    },
    // Single pad on inner4 layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_inner4",
      x: 3,
      y: 0,
      width: 2,
      height: 1,
      layer: "inner4",
      shape: "rect",
    },
    // Single pad on inner5 layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_inner5",
      x: 9,
      y: 0,
      width: 2,
      height: 1,
      layer: "inner5",
      shape: "rect",
    },
    // Single pad on inner6 layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_inner6",
      x: 15,
      y: 0,
      width: 2,
      height: 1,
      layer: "inner6",
      shape: "rect",
    },
    // Single pad on bottom layer
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pcb_smtpad_bottom",
      x: 21,
      y: 0,
      width: 2,
      height: 1,
      layer: "bottom",
      shape: "rect",
    }
</details>

### PR DESCRIPTION
**Pull request by RaghavArora14**
https://github.com/user-attachments/assets/2460589c-7054-439b-abf3-870490fe9708

## Issue Summary
The 8-layer PCB viewer had two critical visibility problems: (1) inner layers 5 and 6 weren't displaying when viewing the top layer by default, and (2) the top layer would completely disappear when any other layer was selected. The root cause was threefold: a missing inner3 color mapping in LAYER_NAME_TO_COLOR, an incorrect DEFAULT_DRAW_ORDER that placed inner layers at the end causing them to render with the lowest z-index values, and a flawed orderAndFadeLayers() function that positioned the selected foreground layer early in the rendering order instead of on top.

## Changes Made
I fixed the color mapping by adding the missing inner3 entry, reordered DEFAULT_DRAW_ORDER to properly stack layers from bottom-to-top (board → inner6 through inner1 → bottom → top), and restructured orderAndFadeLayers() to place the foreground layer at the end of the order array so it always receives the highest z-index. I also added proper TypeScript typing to the eight-layer fixture and created a new overlapping-layers-test fixture with all pads at the same position to visually verify that the selected layer always appears on top with full opacity while other layers remain visible at 50% opacity beneath it. These changes ensure all 8 layers are visible and the selected layer always has the highest z-index for proper stacking behavior.

## New Files Created
eight-layer-circuit.fixture.tsx: This fixture was created to properly test the maximum 8-layer PCB configuration with correct TypeScript typing using AnyCircuitElement[]. It places one pad per layer side-by-side to verify that all layers (top, inner1-6, bottom) are visible in the layer dropdown and render correctly when selected individually or when viewing the top layer by default.

overlapping-layers-test.fixture.tsx: This specialized test fixture was created to definitively verify the z-index stacking fix by placing all 8 layers' pads at the exact same position (0, 0) with decreasing sizes, creating a visual "bullseye" effect. This makes it immediately obvious which layer is rendered on top when selected, allowing developers to quickly verify that the selected layer always appears fully opaque with the highest z-index while all other layers remain visible at 50% opacity beneath it.

fixes #398

### CODE REVIEW

**Review by seveibar — APPROVED** [review]

File: src/lib/Drawer.ts [hunk 1]
```diff
@@ -490,22 +490,29 @@ export class Drawer {
           ? "bottom_silkscreen"
           : "",
     ])
+
+    // Build order with foregroundLayer at the end (highest z-index)
     const order = [
-      "drill",
       "board",
-      foregroundLayer,
+      "drill",
```
Comment (seveibar) [inline src/lib/Drawer.ts]: @RaghavArora14 this caused a production issue with a customer: https://discord.com/channels/1233487248129921135/1353415621995397172/1433549023637405747
